version: '3.5'
services:

  db:
    image: postgres
    restart: always
    container_name: postgres _db
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

